# Generated by Django 2.0.4 on 2018-07-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
