# Generated by Django 2.0.4 on 2018-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_delete_symbol'),
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='trackers',
            field=models.ManyToManyField(to='investor.Investor'),
        ),
    ]
