# Generated by Django 2.0.4 on 2018-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_symbol_trackers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
